name: shopify_example
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  logging: ^1.2.0
  flutter_native_splash: ^2.4.0
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  go_router: ^13.2.4
  theme_tailor: ^3.0.1
  json_annotation: ^4.8.1
  dio: ^5.4.2+1
  graphql_flutter: ^5.1.2
  graphql: ^5.1.3
  equatable: ^2.0.5
  dev: ^1.0.0
  go_router_builder: ^2.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  freezed: ^2.5.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  generate: true
